# Generated by Django 4.0.3 on 2022-04-04 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_alter_meetup_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='date',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='organizer_email',
        ),
        migrations.RemoveField(
            model_name='meetup',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
